language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=availability DB=mysql
  global:
      - secure: "mF+LYvAgZauto0g3knD6wqd3wz3TEiIFEc1IhJDHWsqSjTr371xxk8n1RmrbqoRYpcRutxBtdItvp531SbLjyuo7WJ/yW4VG9k0vh8p1Vxa6x9OreqFmwibDCtO0qwewrqNJzsH4ktPlWracMv6tLNdIJyEhmp8zLQ7etzmoAJ+YGwI7Jtib7r2Mrrplfyf/AK7Vn59QNIKV33vZ7FhCPON6+N2gsuvDG2qS0ulrc/SKujXHyVfaVB7j3ZEQNpuaZC5ZANl5y3FbsgpjUWJPjAt+O9o4Xq+rFGzaoVGsB5IwRLIDiNQye4tgvFDKWzEruslGtfXxOFbOAeD9og+jSoACQ62/vzNwzp8J68+ppDtY0KPp9iOMjAivErv/niF0Ed7059tjR3Z5fyZBr1mxPXY6v3ZKlJ+1IKy+sJcSho/rGhBrfQW8UOMzi08O/ZrXyMMeCZuqByR8BGQtLmEmNZGt0fIGBV4L3NlGG6KaBHUJVpfru2rHkSjM6u1/+v5YUt5f79eyt+BnVNaaTx0Tn8HbE9tcouk2h4VeocGHpskO0oHx5kcxNRJ0Tj9oiJZ0zcRrU0K1ulpLaUAVvszqPTbV88U5UoaggJ987SAeM3xrhG0yBHvrG0gRQfJ5BUouVehadEVEWBgD37UIhKnd8rC2uISwXfxYxaoi2UiqJvM="
      - GIT_COMMITTER_NAME=RyujiAMANO
      - GIT_COMMITTER_EMAIL=ryuji@ryus.co.jp
      - GIT_AUTHOR_NAME=RyujiAMANO
      - GIT_AUTHOR_EMAIL=ryuji@ryus.co.jp

matrix:
    allow_failures:
    # PHP 7.4 testing is allowed to fail because the GD extension and ZipArchive is not packaged on Travis CI yet.
    # See https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/9
    - php: 7.4

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
